#spring:
#  kafka:
#    bootstrap-servers: ${kafka_bootstrap_servers:192.168.99.100:9092}
#    consumer:
#      auto-offset-reset: earliest
#      group-id: example
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      max-poll-records: 1
#      fetch-max-wait: 36000
#      enable-auto-commit: false
#      client-id: example
#    producer:
#      client-id: example
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      retries: 2
#    jaas:
#      enabled: true
#    listener:
#      poll-timeout: 1800000
#      concurrency: 1
#      ack-mode: manual_immediate
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.99.100:9092
      group-id: app
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 192.168.99.100:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer